#!/bin/bash
set -ex

version="$DOCKER_TAG"

if [ "$version" == latest ] ; then
    version=develop
elif [ "$VERSION" == stable ] ; then
    version=master
fi

if [ -z "$IMAGE_NAME" ]; then
    IMAGE_NAME="$DOCKER_REPO:$DOCKER_TAG"
fi

time docker image build \
    --build-arg AIIDA_VERSION="$version" \
    --tag "$IMAGE_NAME" \
    .
